apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: curiefense-access-logs-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      curiefense: "enabled"
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        config:
          access_log:
            - name: "envoy.http_grpc_access_log"
              typed_config:
                "@type": type.googleapis.com/envoy.config.accesslog.v2.HttpGrpcAccessLogConfig
                common_config:
                  log_name: "send_GRPC_log_to_curielogger"
                  grpc_service:
                    google_grpc:
                      target_uri: "curielogger.{{ $.Values.global.proxy.curiefense_namespace }}:9001"
                      stat_prefix: "curielogger_grpc"
